### ISSUE TITLE
mvn package test failed

### ISSUE THREAD

**Issue by hcchien** [huaban/elasticsearch-analysis-jieba#14]
env:
mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-34-generic", arch: "amd64", family: "unix"

error message:
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.784 sec <<< FAILURE! - in org.elasticsearch.index.analysis.JiebaAnalyzerTest
testSegModeOther(org.elasticsearch.index.analysis.JiebaAnalyzerTest)  Time elapsed: 0.025 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
        at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:163)
        at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:186)
        at org.elasticsearch.index.analysis.JiebaAnalyzer$DefaultSetHolder.loadDefaultStopWordSet(JiebaAnalyzer.java:65)
        at org.elasticsearch.index.analysis.JiebaAnalyzer$DefaultSetHolder.<clinit>(JiebaAnalyzer.java:53)
        at org.elasticsearch.index.analysis.JiebaAnalyzer.loadStopWords(JiebaAnalyzer.java:80)
        at org.elasticsearch.index.analysis.JiebaAnalyzer.<init>(JiebaAnalyzer.java:95)
        at org.elasticsearch.index.analysis.JiebaAnalyzerTest.testSegModeOther(JiebaAnalyzerTest.java:107)

**Comment by piaolingxue** [comment]
@hcchien 已修复
