### ISSUE TITLE
Test case failure caused by wrong path

### ISSUE THREAD

**Issue by xiaochutian** [huaban/elasticsearch-analysis-jieba#15]
Cased by: **C:\Users\xiaochutian\Desktop\elasticsearch-analysis-jieba\data\jieba: load user dict failure!**
There are no path like **${jieba_root}/data/jieba/user.dict**
The 'user.dict' file is in dir **${jieba_root}/config/jieba**

The error message in ./target/surefire-reports/TEST-org.elasticsearch.index.analysis.JiebaAnalyzerTest.xml:
```
<testcase classname="org.elasticsearch.index.analysis.JiebaAnalyzerTest" name="testSegModeOther" time="0.003">
    <error type="java.lang.ExceptionInInitializerError">java.lang.ExceptionInInitializerError
	at org.elasticsearch.index.analysis.JiebaAnalyzer.loadStopWords(JiebaAnalyzer.java:80)
	at org.elasticsearch.index.analysis.JiebaAnalyzer.&lt;init&gt;(JiebaAnalyzer.java:95)
	at org.elasticsearch.index.analysis.JiebaAnalyzerTest.testSegModeOther(JiebaAnalyzerTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NullPointerException
	at java.io.Reader.&lt;init&gt;(Reader.java:78)
	at java.io.InputStreamReader.&lt;init&gt;(InputStreamReader.java:129)
	at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:163)
	at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:186)
	at org.elasticsearch.index.analysis.JiebaAnalyzer$DefaultSetHolder.loadDefaultStopWordSet(JiebaAnalyzer.java:65)
	at org.elasticsearch.index.analysis.JiebaAnalyzer$DefaultSetHolder.&lt;clinit&gt;(JiebaAnalyzer.java:53)
	... 32 more
</error>
    <system-out>initialize user dictionary:C:\Users\xiaochutian\Desktop\elasticsearch-analysis-jieba\data\jieba
</system-out>
    <system-err>C:\Users\xiaochutian\Desktop\elasticsearch-analysis-jieba\data\jieba: load user dict failure!
</system-err>
  </testcase>

```

**Comment by hcchien** [comment]
compile 可以成功 pass tests 了
可是按照 README 的 cp 了 .jar 到 plugin/jieba/ 底下
重起 elasticsearch 後發生了錯誤


[2016-08-22 14:58:35,544][INFO ][plugins                  ] [Jean Grey] modules [reindex, lang-expression, lang-groovy], plugins [jieba, cloud-gce], sites []
[2016-08-22 14:58:35,588][INFO ][env                      ] [Jean Grey] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [17.4gb], net total_space [
19.3gb], spins? [possibly], types [ext4]
[2016-08-22 14:58:35,589][INFO ][env                      ] [Jean Grey] heap size [1015.6mb], compressed ordinary object pointers [true]
[2016-08-22 14:58:35,589][WARN ][env                      ] [Jean Grey] max file descriptors [65535] for elasticsearch process likely too low, consider increasing t
o at least [65536]
[2016-08-22 14:58:41,861][ERROR][bootstrap                ] Guice Exception: java.lang.ExceptionInInitializerError
Likely root cause: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
        at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:163)
        at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:186)
        at org.elasticsearch.index.analysis.JiebaAnalyzer$DefaultSetHolder.loadDefaultStopWordSet(JiebaAnalyzer.java:65)
        at org.elasticsearch.index.analysis.JiebaAnalyzer$DefaultSetHolder.<clinit>(JiebaAnalyzer.java:53)
        at org.elasticsearch.index.analysis.JiebaAnalyzer.loadStopWords(JiebaAnalyzer.java:80)
        at org.elasticsearch.index.analysis.JiebaAnalyzer.<init>(JiebaAnalyzer.java:95)
        at org.elasticsearch.index.analysis.JiebaAnalyzer.<init>(JiebaAnalyzer.java:85)
        at org.elasticsearch.indices.analysis.JiebaIndicesAnalysis.<init>(JiebaIndicesAnalysis.java:34)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by piaolingxue** [comment]
多谢反馈，我彻底修复下

**Comment by piaolingxue** [comment]
@hcchien 已更新，现在 2.x 的版本都可以通过 `./bin/plugin` 直接安装了
