### ISSUE TITLE
out of memory while compile the app

### ISSUE THREAD

**Issue by yozhang** [huaban/elasticsearch-analysis-jieba#4]
Running org.elasticsearch.index.analysis.JiebaAnalyzerTest
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 32.817 sec <<< FAILURE!
test(org.elasticsearch.index.analysis.JiebaAnalyzerTest)  Time elapsed: 21.11 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
	at java.util.regex.Pattern.closure(Pattern.java:2737)
	at java.util.regex.Pattern.sequence(Pattern.java:1889)
	at java.util.regex.Pattern.expr(Pattern.java:1752)
	at java.util.regex.Pattern.compile(Pattern.java:1460)
	at java.util.regex.Pattern.<init>(Pattern.java:1133)
	at java.util.regex.Pattern.compile(Pattern.java:823)
	at java.lang.String.split(String.java:2292)
	at java.lang.String.split(String.java:2334)
	at com.huaban.analysis.jieba.WordDictionary.loadDict(WordDictionary.java:62)
	at com.huaban.analysis.jieba.WordDictionary.getInstance(WordDictionary.java:32)
	at org.elasticsearch.index.analysis.JiebaAnalyzer.<init>(JiebaAnalyzer.java:88)
	at org.elasticsearch.index.analysis.JiebaAnalyzerTest.test(JiebaAnalyzerTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

org.elasticsearch.index.analysis.JiebaAnalyzerTest  Time elapsed: 10.747 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space

Results :

Tests in error: 
  test(org.elasticsearch.index.analysis.JiebaAnalyzerTest): Java heap space
  org.elasticsearch.index.analysis.JiebaAnalyzerTest: Java heap space

Tests run: 3, Failures: 0, Errors: 2, Skipped: 0

could you please give me some advices?

**Comment by piaolingxue** [comment]
请使用 oracle 的 jvm。
